# Generated by Django 4.1.13 on 2026-02-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orders_and_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
